name: Build

on:
  - push
  - pull_request

jobs:
  compile-sketches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp8266:esp8266:d1_mini
          platforms: |
            - name: esp8266:esp8266
              version: 3.1.2
              source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
          sketch-paths: |
            - steampunk-clock.ino
          libraries: |
            - name: Adafruit BusIO
              version: 1.17.4
            - name: Adafruit PCF8574
              version: 1.1.2
            - name: OneButton
              version: 2.6.1
            - name: RTClib
              version: 2.1.4
            - name: WiFiManager
              version: 2.0.17