name: Build

on:
  - push
  - pull_request

jobs:
  compile-sketches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp8266:esp8266
          platforms: |
            - name: esp8266:esp8266
              version: 3.1.2
              index_url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
          sketch-paths: |
            - steampunk-clock.ino
          libraries: |
            - name: Adafruit BusIO
            - name: Adafruit PCF8574
            - name: OneButton
            - name: RTClib
            - name: WiFiManager